const translations = {
    "en": {
        //Pizzas
        "pizza1_title": "Veggie Pizza",
        "pizza1_desc": "Fresh dough, rich tomato sauce, melted cheese.",
        "pizza1_price": "20,000 IQD",
        "pizza2_title": "Pepperoni Pizza",
        "pizza2_desc": "Spicy pepperoni, mozzarella, and our signature tomato sauce.",
        "pizza2_price": "25,000 IQD",
        "pizza3_title": "Margherita Pizza",
        "pizza3_desc": "Classic Margherita with fresh basil and mozzarella.",
        "pizza3_price": "22,000 IQD",
        "pizza4_title": "Classic Pizza",
        "pizza4_desc": "Classic Margherita with fresh basil and mozzarella.",
        "pizza4_price": "15,000 IQD",
        "pizza5_title": "Four Cheese Pizza",
        "pizza5_desc": "Four types of cheese with fresh basil and mozzarella.",
        "pizza5_price": "18,000 IQD",
        "pizza6_title": "BBQ Chicken Pizza",
        "pizza6_desc": "BBQ sauce, chicken, mozzarella, and fresh basil.",
        "pizza6_price": "24,000 IQD",
        //Drinks
        "drink1_title": "Avocado Smoothie",
        "drink1_desc": "Fresh avocado, milk, honey, and a hint of vanilla.",
        "drink1_price": "3,500 IQD",
        "drink2_title": "Fruit Juice",
        "drink2_desc": "Fresh orange juice, apple juice, and a touch of honey.",
        "drink2_price": "3,000 IQD",
        "drink3_title": "Milk Banana",
        "drink3_desc": "Fresh banana, milk, and a touch of honey.",
        "drink3_price": "2,500 IQD",
        "drink4_title": "Pineapple Smoothie",
        "drink4_desc": "Sweet pineapple, coconut milk, and a touch of honey.",
        "drink4_price": "3,200 IQD",
        "drink5_title": "Kiwi Smoothie",
        "drink5_desc": "Tangy kiwi, banana, and a splash of orange juice.",
        "drink5_price": "3,000 IQD",
        "drink6_title": "Polo Juice",
        "drink6_desc": "Refreshing mint and lime blend.",
        "drink6_price": "2,000 IQD",
        //Sandwiches
        "sandwich1_title": "Chicken Sandwich",
        "sandwich1_desc": "Grilled chicken breast, fresh lettuce, tomato, and mayonnaise on a toasted bun.",
        "sandwich1_price": "15,000 IQD",
        "sandwich2_title": "Beef Sandwich",
        "sandwich2_desc": "Tender beef slices, caramelized onions, Swiss cheese, and horseradish sauce on rye bread.",
        "sandwich2_price": "18,000 IQD",
        "sandwich3_title": "Veggie Sandwich",
        "sandwich3_desc": "Fresh vegetables, hummus, feta cheese, and balsamic glaze on whole wheat bread.",
        "sandwich3_price": "12,000 IQD",
        "sandwich4_title": "Tuna Sandwich",
        "sandwich4_desc": "Tuna salad with celery, red onion, and lemon juice on sourdough bread.",
        "sandwich4_price": "14,000 IQD",
        "sandwich5_title": "Club Sandwich",
        "sandwich5_desc": "Triple-decker sandwich with turkey, bacon, lettuce, tomato, and mayonnaise.",
        "sandwich5_price": "16,000 IQD",
        "sandwich6_title": "BLT Sandwich",
        "sandwich6_desc": "Classic bacon, lettuce, and tomato sandwich with mayonnaise on toasted bread.",
        "sandwich6_price": "13,000 IQD"
    },
    "ar": {
        //Pizzas
        "pizza1_title": "بيتزا خضروات",
        "pizza1_desc": "عجينة طازجة، صلصة طماطم غنية، جبنة ذائبة.",
        "pizza1_price": "20,000 دينار عراقي",
        "pizza2_title": "بيتزا بيبروني",
        "pizza2_desc": "بيبروني حار، موزاريلا، وصلصة طماطم مميزة.",
        "pizza2_price": "25,000 دينار عراقي",
        "pizza3_title": "بيتزا مارغريتا",
        "pizza3_desc": "مارغريتا كلاسيكية مع ريحان طازج وموزاريلا.",
        "pizza3_price": "22,000 دينار عراقي",
        "pizza4_title": "بيتزا كلاسيكية",
        "pizza4_desc": "بيتزا كلاسيكية مع ريحان طازج وموزاريلا.",
        "pizza4_price": "15,000 دينار عراقي",
        "pizza5_title": "بيتزا أجبان",
        "pizza5_desc": "أربعة أنواع من الجبن مع ريحان طازج وموزاريلا.",
        "pizza5_price": "18,000 دينار عراقي",
        "pizza6_title": "بيتزا دجاج باربيكيو",
        "pizza6_desc": "صلصة باربيكيو، دجاج، موزاريلا، وريحان طازج.",
        "pizza6_price": "24,000 دينار عراقي",
        //Drinks
        "drink1_title": "سموثي الأفوكادو",
        "drink1_desc": "أفوكادو طازج، حليب، عسل، وقليل من الفانيليا.",
        "drink1_price": "3,500 دينار عراقي",
        "drink2_title": "عصير فواكه",
        "drink2_desc": "عصير برتقال طازج، عصير تفاح، وقليل من العسل.",
        "drink2_price": "3,000 دينار عراقي",
        "drink3_title": "ميلك بنانا",
        "drink3_desc": "موز طازج، حليب، وقليل من العسل.",
        "drink3_price": "2,500 دينار عراقي",
        "drink4_title": "سموثي الأناناس",
        "drink4_desc": "أناناس حلو، حليب جوز الهند، وقليل من العسل.",
        "drink4_price": "3,200 دينار عراقي",
        "drink5_title": "سموثي الكيوي",
        "drink5_desc": "كيوي منعش، موز، وقليل من عصير البرتقال.",
        "drink5_price": "3,000 دينار عراقي",
        "drink6_title": "عصير بولو",
        "drink6_desc": "مزيج منعش من النعناع والليمون.",
        "drink6_price": "2,000 دينار عراقي",
        //Sandwiches
        "sandwich1_title": "ساندويتش دجاج",
        "sandwich1_desc": "صدر دجاج مشوي، خس طازج، طماطم، ومايونيز على خبز محمص.",
        "sandwich1_price": "15,000 دينار عراقي",
        "sandwich2_title": "ساندويتش لحم",
        "sandwich2_desc": "شرائح لحم طرية، بصل مكرمل، جبنة سويسرية، وصلصة فجل حار على خبز الجاودار.",
        "sandwich2_price": "18,000 دينار عراقي",
        "sandwich3_title": "ساندويتش خضروات",
        "sandwich3_desc": "خضروات طازجة، حمص، جبنة فيتا، وصلصة بلسميك على خبز القمح الكامل.",
        "sandwich3_price": "12,000 دينار عراقي",
        "sandwich4_title": "ساندويتش تونة",
        "sandwich4_desc": "سلطة تونة مع كرفس وبصل أحمر وعصير ليمون على خبز الساوردو.",
        "sandwich4_price": "14,000 دينار عراقي",
        "sandwich5_title": "كلوب ساندويتش",
        "sandwich5_desc": "ساندويتش ثلاثي الطبقات مع ديك رومي، لحم مقدد، خس، طماطم، ومايونيز.",
        "sandwich5_price": "16,000 دينار عراقي",
        "sandwich6_title": "ساندويتش بيكن وخس وطماطم",
        "sandwich6_desc": "ساندويتش كلاسيكي من لحم مقدد وخس وطماطم مع مايونيز على خبز محمص.",
        "sandwich6_price": "13,000 دينار عراقي"
    },
    "ku": {
        //Pizzas
        "pizza1_title": "پیتزای سەوزەوات",
        "pizza1_desc": "هەویر تازە، سۆسی تەماتۆی دەوڵەمەند، پەنیرتوو.",
        "pizza1_price": "20,000 دیناری عێراقی",
        "pizza2_title": "پیتزای پپیرۆنی",
        "pizza2_desc": "پپیرۆنی تیژ، مۆزاریلا، و سۆسی تەماتۆی تایبەت.",
        "pizza2_price": "25,000 دیناری عێراقی",
        "pizza3_title": "پیتزای مارگریتا",
        "pizza3_desc": "مارگریتای کلاسیک لەگەڵ ڕەیحانی تازە و مۆزاریلا.",
        "pizza3_price": "22,000 دیناری عێراقی",
        "pizza4_title": "پیتزای کلاسیک",
        "pizza4_desc": "پیتزای کلاسیک لەگەڵ ڕەیحانی تازە و مۆزاریلا.",
        "pizza4_price": "15,000 دیناری عێراقی",
        "pizza5_title": "پیتزای چوار پەنیر",
        "pizza5_desc": "چوار جۆر پەنیر لەگەڵ ڕەیحانی تازە و مۆزاریلا.",
        "pizza5_price": "18,000 دیناری عێراقی",
        "pizza6_title": "پیتزای مریشک باربیکیو",
        "pizza6_desc": "سۆسی باربیکیو، مریشک، مۆزاریلا، و ڕەیحانی تازە.",
        "pizza6_price": "24,000 دیناری عێراقی",
        //Drinks
        "drink1_title": "سمۆسێی ئەڤۆکادۆ",
        "drink1_desc": "ئەڤۆکادۆی تازە، شیر، هەنگوین، و کەمێک ڤانێلا.",
        "drink1_price": "3,500 دیناری عێراقی",
        "drink2_title": "شیرینی میوە",
        "drink2_desc": "شیرینی پرتەقاڵی تازە، شیرینی سێو، و کەمێک هەنگوین.",
        "drink2_price": "3,000 دیناری عێراقی",
        "drink3_title": "میلک بنانا",
        "drink3_desc": "مۆزێکی تازە، شیر، و کەمێک هەنگوین.",
        "drink3_price": "2,500 دیناری عێراقی",
        "drink4_title": "سمۆسێی ئەناناس",
        "drink4_desc": "ئەناناسی شیرین، شیری کۆکۆس، و کەمێک هەنگوین.",
        "drink4_price": "3,200 دیناری عێراقی",
        "drink5_title": "سمۆسێی کیوی",
        "drink5_desc": "کیوی ترش، مۆز، و کەمێک شیرینی پرتەقاڵ.",
        "drink5_price": "3,000 دیناری عێراقی",
        "drink6_title": "شیرینی پۆڵۆ",
        "drink6_desc": "تێکەڵەیەکی تازە لە نەعناع و لیمۆ.",
        "drink6_price": "2,000 دیناری عێراقی",
        //Sandwiches
        "sandwich1_title": "ساندویچی مریشک",
        "sandwich1_desc": "سنگ مریشک، خەس، تەماتە، و مایۆنیز لەسەر نانی تێستکراو.",
        "sandwich1_price": "15,000 دیناری عێراقی",
        "sandwich2_title": "ساندویچی گۆشت",
        "sandwich2_desc": "پارچە گۆشتی نەرم، پیاز، پەنیر سویسری، و سۆسی خێردەل لەسەر نانی ڕای.",
        "sandwich2_price": "18,000 دیناری عێراقی",
        "sandwich3_title": "ساندویچی سەوزەوات",
        "sandwich3_desc": "سەوزەواتی تازە، حوموس، پەنیر فێتا، و سۆسی بالسامیک لەسەر نانی گەنم.",
        "sandwich3_price": "12,000 دیناری عێراقی",
        "sandwich4_title": "ساندویچی تونا",
        "sandwich4_desc": "سەڵاتەی تونا لەگەڵ کەرەوز و پیاز و ئاوی لیمۆ لەسەر نانی ساوەردۆ.",
        "sandwich4_price": "14,000 دیناری عێراقی",
        "sandwich5_title": "کلۆب ساندویچ",
        "sandwich5_desc": "ساندویچی سێ قات لەگەڵ تورکی، بیکن، خەس، تەماتە، و مایۆنیز.",
        "sandwich5_price": "16,000 دیناری عێراقی",
        "sandwich6_title": "ساندویچی بیکن و خەس و تەماتە",
        "sandwich6_desc": "ساندویچی کلاسیک لە بیکن و خەس و تەماتە لەگەڵ مایۆنیز لەسەر نانی تێستکراو.",
        "sandwich6_price": "13,000 دیناری عێراقی"
    }
};

function setLanguage(language) {
    const elements = document.querySelectorAll("[data-key]");
    elements.forEach(element => {
        const key = element.getAttribute("data-key");
        element.textContent = translations[language][key];
        if (language === "ar" || language === "ku") {
            element.style.direction = "rtl";
            element.style.textAlign = "right";
        } else {
            element.style.direction = "ltr";
            element.style.textAlign = "left";
        }
    });
}
